Repository btcven/radio-firmware, pull requests merged in 2020-06, with the labels that each got.

#103 aodvv2: refactor Router Client Set
  main.c
  sys/include/net/aodvv2/rcs.h
  sys/net/aodvv2/Kconfig
  sys/net/aodvv2/aodvv2.c
  sys/net/aodvv2/aodvv2_client.c
  sys/net/aodvv2/aodvv2_rcs.c
  sys/net/aodvv2/rfc5444_reader.c
  sys/net/vaina/vaina.c
  sys/shell_extended/sc_aodvv2.c
  sys/shell_extended/shell_extended.c
Labels: Area: routing, Status: Ready For Review

#105 aodvv2: use prefix length correctly
  sys/include/net/aodvv2/aodvv2.h
  sys/include/net/aodvv2/lrs.h
  sys/include/net/aodvv2/rcs.h
  sys/include/net/aodvv2/rfc5444.h
  sys/include/net/metric.h
  sys/net/aodvv2/aodvv2.c
  sys/net/aodvv2/aodvv2_lrs.c
  sys/net/aodvv2/aodvv2_rcs.c
  sys/net/aodvv2/rfc5444_compat.c
  sys/net/aodvv2/rfc5444_reader.c
  sys/net/aodvv2/rfc5444_writer.c
  sys/shell_extended/sc_aodvv2.c
Labels: Area: routing, Type: enhancement

#106 aodvv2: refactor Multicast Mesage Set
  main.c
  sys/include/net/aodvv2/mcmsg.h
  sys/include/net/aodvv2/rfc5444.h
  sys/include/net/aodvv2/rreqtable.h
  sys/include/net/manet.h
  sys/net/aodvv2/Kconfig
  sys/net/aodvv2/aodvv2.c
  sys/net/aodvv2/aodvv2_mcmsg.c
  sys/net/aodvv2/aodvv2_rreqtable.c
  sys/net/aodvv2/rfc5444_reader.c
  sys/net/manet/manet.c
  sys/shell_extended/sc_aodvv2.c
Labels: Area: routing, Status: Ready For Review

#104 Create AUTHORS
  AUTHORS
Labels: Status: Ready For Review

#107 vaina: add pfx_len field to RCS ops
  Makefile
  dist/tools/vaina/autoconfigure.sh
  dist/tools/vaina/src/cli.yml
  dist/tools/vaina/src/msg.rs
  dist/tools/vaina/src/rcs.rs
  sys/include/net/vaina.h
  sys/net/aodvv2/aodvv2_mcmsg.c
  sys/net/vaina/vaina.c
Labels: Area: routing, Status: Ready For Review, Type: enhancement

#112 radio-firmware: refactor bug-prone code on AODVv2
  Makefile
  main.c
  sys/Makefile
  sys/Makefile.dep
  sys/include/net/aodvv2.h
  sys/include/net/aodvv2/conf.h
  sys/include/net/aodvv2/lrs.h
  sys/include/net/aodvv2/mcmsg.h
  sys/include/net/aodvv2/rfc5444.h
  sys/net/Makefile
  sys/net/aodvv2/Kconfig
  sys/net/aodvv2/Kconfig.timers
  sys/net/aodvv2/aodvv2.c
  sys/net/aodvv2/aodvv2_buffer.c
  sys/net/aodvv2/aodvv2_lrs.c
  sys/net/aodvv2/aodvv2_mcmsg.c
  sys/net/aodvv2/aodvv2_reader.c
  sys/net/aodvv2/aodvv2_reader.h
  sys/net/aodvv2/aodvv2_writer.c
  sys/net/aodvv2/aodvv2_writer.h
  sys/net/aodvv2/rfc5444_compat.c
  sys/net/aodvv2/rfc5444_compat.h
  sys/oonf_api/Makefile
  sys/shell_extended/find_route.c
Labels: Area: routing, Status: Ready For Review, Type: enhancement

#114 sys/drivers: add bq27441 driver
  Makefile
  boards/cc1352p-launchpad/Makefile.dep
  boards/cc1352p-launchpad/Makefile.features
  boards/cc1352p-launchpad/Makefile.include
  boards/cc1352p-launchpad/board.c
  boards/cc1352p-launchpad/dist/cc1352p1_XDS110.ccxml
  boards/cc1352p-launchpad/dist/cc1352p1_XDS110.dat
  boards/cc1352p-launchpad/dist/cc1352p1_gdb.conf
  boards/cc1352p-launchpad/doc.txt
  boards/cc1352p-launchpad/include/board.h
  boards/cc1352p-launchpad/include/periph_conf.h
  boards/turpial/Kconfig
  boards/turpial/Makefile.features
  boards/turpial/dist/cc1312r1f3_XDS110.ccxml
  boards/turpial/dist/cc1312r1f3_XDS110.dat
  boards/turpial/dist/cc1312r1f3_gdb.conf
  boards/turpial/include/periph_conf.h
  sys/Makefile
  sys/Makefile.dep
  sys/Makefile.include
  sys/drivers/Makefile
  sys/drivers/bq27441/Makefile
  sys/drivers/bq27441/bq27441.c
  sys/drivers/bq27441/include/bq27441_params.h
  sys/drivers/bq27441/include/bq27441_regs.h
  sys/include/bq27441.h
  tests/Makefile.tests_common
  tests/README.md
  tests/drivers_bq27441/Makefile
  tests/drivers_bq27441/main.c
Labels: Type: enhancement

#115 vaina: fix next_hop on NIB_ADD
  sys/net/vaina/vaina.c
Labels: Area: routing, Status: Ready For Review, Type: bug

#116 drivers/bq27441: fix unused variable
  sys/drivers/bq27441/bq27441.c
Labels: Area: testing, Status: Ready For Review, Type: bug

#118 .github: add testing workflow
  .github/workflows/testing.yml
  CONTRIBUTING.md
  boards/turpial/include/periph_conf.h
  sys/include/net/aodvv2/seqnum.h
  sys/include/net/metric.h
  sys/net/aodvv2/aodvv2_reader.c
  sys/net/aodvv2/aodvv2_writer.c
Labels: Area: testing, Status: Ready For Review, Type: enhancement

#123 Update [dev] from [master]
  sys/net/vaina/vaina.c
Labels: Area: radio, Type: bug

#124 net/aodvv2: small cleanups
  sys/Makefile.dep
  sys/include/net/aodvv2/conf.h
  sys/include/net/aodvv2/mcmsg.h
  sys/net/aodvv2/Kconfig
  sys/net/aodvv2/aodvv2.c
  sys/net/aodvv2/aodvv2_lrs.c
  sys/net/aodvv2/aodvv2_mcmsg.c
  sys/net/aodvv2/aodvv2_reader.c
  sys/oonf_api/common/Makefile
  sys/oonf_api/common/autobuf.c
  sys/oonf_api/rfc5444/rfc5444.h
  tests/Makefile.tests_common
Labels: Area: routing, Status: Ready For Review, Type: enhancement
